version: '3'

services:
  smart-read-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    networks:
      - smartreadnet

    
  smart-read-api:
    restart: unless-stopped
    build: .
    environment:
      - ConnectionStrings:SmartRead=Server=smart-read-sql,1433;Database=SmartRead;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 55992:80
    networks:
      - smartreadnet

networks:
  smartreadnet:
    driver: bridge