// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartRead.API.Database.Context;

namespace SmartRead.API.Migrations
{
    [DbContext(typeof(SmartReadContext))]
    [Migration("20210709062026_korisnikClanakIsKupljenAndOcjena")]
    partial class korisnikClanakIsKupljenAndOcjena
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartRead.API.Database.Clanak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<double>("Cijena")
                        .HasColumnType("float");

                    b.Property<string>("Naslov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Obrisan")
                        .HasColumnType("bit");

                    b.Property<int?>("OdobravateljId")
                        .HasColumnType("int");

                    b.Property<bool>("Odobren")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("OdobravateljId");

                    b.ToTable("Clanci");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutorId = 2,
                            Cijena = 0.12163977470325296,
                            Naslov = "At totam quos asperiores qui reiciendis autem omnis modi.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = @"Eius assumenda velit eveniet amet.
Est consequatur nisi vitae quo soluta."
                        },
                        new
                        {
                            Id = 2,
                            AutorId = 2,
                            Cijena = 0.14441501821596875,
                            Naslov = "Et molestiae distinctio voluptatem consequatur possimus quidem.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "Corporis ipsa illo doloribus sunt qui distinctio rerum. Et ut eveniet maxime voluptates quia deleniti quae culpa dignissimos. Possimus consequatur officiis consectetur quia hic sed quasi quia. Eligendi commodi veniam assumenda mollitia."
                        },
                        new
                        {
                            Id = 3,
                            AutorId = 2,
                            Cijena = 0.37681011686884336,
                            Naslov = "Minus repudiandae velit nihil architecto.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "Facere soluta placeat rerum rerum. Illo esse porro rerum dolores ipsum eos libero. Voluptatem officia iusto iste."
                        },
                        new
                        {
                            Id = 4,
                            AutorId = 2,
                            Cijena = 0.91848535925079389,
                            Naslov = "Laborum aut ipsam veritatis aut ipsam libero et ut soluta.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "qui"
                        },
                        new
                        {
                            Id = 5,
                            AutorId = 2,
                            Cijena = 0.14310940361726535,
                            Naslov = "Enim quis consequuntur voluptatem quidem quidem rerum.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = @"Aut quas veritatis.
Quia fugiat quidem tempora cum consequatur qui nihil et.
Omnis qui iure ipsum consequatur sed laudantium ut rerum aspernatur.
Et praesentium sed sint id a quae sunt numquam.
Est magnam saepe.
Sint ipsa aut."
                        },
                        new
                        {
                            Id = 6,
                            AutorId = 2,
                            Cijena = 0.67232556579277181,
                            Naslov = "Molestiae error earum et perspiciatis et magnam.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "Quidem et natus sapiente ut cupiditate quis occaecati. Itaque voluptate explicabo et numquam. Dolorem qui quos aut at neque distinctio quia reprehenderit."
                        },
                        new
                        {
                            Id = 7,
                            AutorId = 2,
                            Cijena = 0.40996548412831757,
                            Naslov = "Quo numquam in cum corrupti.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "nulla"
                        },
                        new
                        {
                            Id = 8,
                            AutorId = 2,
                            Cijena = 0.44688997764461208,
                            Naslov = "Praesentium quae quis doloribus perspiciatis qui cupiditate.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "Qui sit hic est."
                        },
                        new
                        {
                            Id = 9,
                            AutorId = 2,
                            Cijena = 0.99817851511676725,
                            Naslov = "Aspernatur omnis tempore ut occaecati.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "Nostrum mollitia consequatur nesciunt. Et qui tempora magnam sed harum laboriosam quia at quas. Quo rerum dolorem alias magnam laboriosam ex. Assumenda sed culpa qui molestias dolores necessitatibus est eaque aut."
                        },
                        new
                        {
                            Id = 10,
                            AutorId = 2,
                            Cijena = 0.090240596835613529,
                            Naslov = "Id maiores in et facere sint.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "maxime"
                        },
                        new
                        {
                            Id = 11,
                            AutorId = 2,
                            Cijena = 0.88017939398073564,
                            Naslov = "Magnam et aliquam.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "quidem"
                        },
                        new
                        {
                            Id = 12,
                            AutorId = 2,
                            Cijena = 0.58544304807923875,
                            Naslov = "Quam sint hic labore qui iure maxime ab est.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = @"Accusantium ullam labore vero aut.
Qui veritatis ullam dolore sit quaerat laborum eveniet distinctio.
Suscipit rem reprehenderit vero aut et et sapiente quae sequi.
Mollitia fugiat illum accusantium sed quia et et aut aut.
Qui exercitationem voluptates illum molestias ipsum."
                        },
                        new
                        {
                            Id = 13,
                            AutorId = 2,
                            Cijena = 0.90800641333125831,
                            Naslov = "Et molestiae est quibusdam quo magnam quia eveniet.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "Nobis minima consequatur a."
                        },
                        new
                        {
                            Id = 14,
                            AutorId = 2,
                            Cijena = 0.77834051744003807,
                            Naslov = "Incidunt deleniti modi consequuntur.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "At itaque hic sit explicabo hic consectetur nostrum ducimus. Ex cupiditate doloribus accusamus aperiam aut. Aut nihil magni voluptas quia minus in sit iure."
                        },
                        new
                        {
                            Id = 15,
                            AutorId = 2,
                            Cijena = 0.88800029544532311,
                            Naslov = "Accusantium hic blanditiis facere ducimus sunt officiis.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "Tempora hic aut recusandae ut eveniet qui et sint voluptatem. Vel ducimus dolore excepturi. Asperiores qui sed. Ratione impedit ipsum id voluptatem. Et animi beatae eveniet repellat quia. At et rem sit voluptates."
                        },
                        new
                        {
                            Id = 16,
                            AutorId = 2,
                            Cijena = 0.77669637360456234,
                            Naslov = "Consequuntur placeat totam sint qui est et quia et.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "Qui distinctio qui."
                        },
                        new
                        {
                            Id = 17,
                            AutorId = 2,
                            Cijena = 0.017964642037621065,
                            Naslov = "Dolor molestias libero id reiciendis pariatur ex.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "ut"
                        },
                        new
                        {
                            Id = 18,
                            AutorId = 2,
                            Cijena = 0.8419773964406817,
                            Naslov = "Mollitia mollitia eaque.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "vitae"
                        },
                        new
                        {
                            Id = 19,
                            AutorId = 2,
                            Cijena = 0.46191982341088345,
                            Naslov = "Et qui labore et quia.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = @"Ea soluta et at sint itaque architecto dolores.
Excepturi labore voluptatem vero ad qui ducimus magnam.
Id et laborum sed consequatur perferendis.
Exercitationem voluptatem vel minima consequuntur.
Ab maxime voluptatem quos tempore.
Velit et odit occaecati."
                        },
                        new
                        {
                            Id = 20,
                            AutorId = 2,
                            Cijena = 0.60813400503626747,
                            Naslov = "Occaecati nulla eligendi molestias delectus.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "Eum perferendis sunt aspernatur sequi ipsam. Omnis modi temporibus eligendi at error non consectetur voluptate. Repellendus quisquam tempora voluptas debitis et eum. Vero nulla ipsum est. Amet eum corrupti est totam eaque et dolorem suscipit. Iusto vero minima voluptatem eum."
                        },
                        new
                        {
                            Id = 21,
                            AutorId = 2,
                            Cijena = 0.48563799564057869,
                            Naslov = "Nemo expedita quis repudiandae sit ad error natus tenetur.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = @"Exercitationem totam laborum rerum iusto id enim commodi quo quod.
Facere molestiae qui commodi.
Voluptatibus mollitia sit iste perspiciatis beatae ut sint quia.
Alias odit molestiae neque sint cupiditate hic numquam eaque.
Dolorem repudiandae voluptas quo sint et earum error quas sed."
                        },
                        new
                        {
                            Id = 22,
                            AutorId = 2,
                            Cijena = 0.27249658073880551,
                            Naslov = "Repudiandae omnis culpa ex suscipit ratione voluptate eius.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "Error animi quia odio tempore tempora et. Non velit rem delectus quasi possimus totam eaque ullam. Reiciendis perferendis repellendus iure."
                        },
                        new
                        {
                            Id = 23,
                            AutorId = 2,
                            Cijena = 0.86613755061576958,
                            Naslov = "Ratione qui neque amet.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "Sapiente est quis minima fugit enim et ut suscipit. Qui ad voluptatem odio consequatur molestias animi accusamus aut odit. Hic dicta quo. Voluptas perferendis nostrum sunt. Odio alias ea. Excepturi labore dolor deleniti aliquid qui dolores."
                        },
                        new
                        {
                            Id = 24,
                            AutorId = 2,
                            Cijena = 0.50940551259992906,
                            Naslov = "Eos inventore fugit hic facere suscipit beatae natus.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "Cumque id aut rerum qui aut temporibus ullam."
                        },
                        new
                        {
                            Id = 25,
                            AutorId = 2,
                            Cijena = 0.1664131368354024,
                            Naslov = "Enim iusto qui accusamus.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = @"Est quia sint vel est eius enim.
Dolor veritatis autem voluptatem a perferendis quas sed enim cumque.
Et mollitia sit autem natus molestiae maiores est consequatur.
Voluptas et eius dolorem voluptas aliquid odio et.
Sunt occaecati optio optio libero.
Velit eaque omnis."
                        },
                        new
                        {
                            Id = 26,
                            AutorId = 2,
                            Cijena = 0.25749879109556728,
                            Naslov = "Ipsam esse ipsum aut molestiae aut qui maxime tenetur.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "Earum et qui qui sequi iusto consectetur. Et ipsam alias est sit aut ut distinctio. Ratione reprehenderit iusto occaecati animi. Repudiandae architecto laboriosam qui temporibus a. Nulla ea totam doloribus facere qui eius eius."
                        },
                        new
                        {
                            Id = 27,
                            AutorId = 2,
                            Cijena = 0.34439847261849721,
                            Naslov = "Commodi quas cumque repellat velit natus unde.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = @"Ea aut natus amet aut laboriosam vero sed.
Illum ipsa in nihil quis totam facilis eos."
                        },
                        new
                        {
                            Id = 28,
                            AutorId = 2,
                            Cijena = 0.85853580285726849,
                            Naslov = "Qui dignissimos quia.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "Sit ut iure. Excepturi temporibus est porro modi nostrum ipsa. Minima reiciendis esse deserunt soluta rem odio natus sapiente. Sit non assumenda nihil sed in dolorum nostrum veniam. Voluptas fugit asperiores odio totam aperiam ut accusantium ut nobis. Beatae molestiae nulla vero consequatur quidem."
                        },
                        new
                        {
                            Id = 29,
                            AutorId = 2,
                            Cijena = 0.12406041106398237,
                            Naslov = "Et qui ut aut eius similique eos minus dicta.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = @"Non consequatur quia.
Dolorem voluptatibus aut."
                        },
                        new
                        {
                            Id = 30,
                            AutorId = 2,
                            Cijena = 0.34713382196944853,
                            Naslov = "Ut velit nostrum ad ipsam magnam aspernatur et.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = @"Omnis provident harum laudantium provident alias omnis accusamus est ullam.
Dignissimos quasi officia omnis.
Nemo vel eligendi.
Distinctio minus fugit quam eaque earum.
Ut ipsam omnis vel occaecati placeat quaerat suscipit in.
Distinctio et neque quia aut sint."
                        },
                        new
                        {
                            Id = 31,
                            AutorId = 2,
                            Cijena = 0.17497457199495964,
                            Naslov = "Ut modi est.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "Odit officiis blanditiis minima doloremque esse non molestiae officia. Officiis iste pariatur corrupti. Eligendi consequatur aliquam sequi optio facilis ipsam provident."
                        },
                        new
                        {
                            Id = 32,
                            AutorId = 2,
                            Cijena = 0.70585453496587203,
                            Naslov = "Eius voluptas suscipit quasi quisquam ratione qui.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "delectus"
                        },
                        new
                        {
                            Id = 33,
                            AutorId = 2,
                            Cijena = 0.48295105317744941,
                            Naslov = "Exercitationem voluptatibus nemo voluptatibus neque ut voluptates asperiores.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "Libero eos blanditiis ad velit iusto est."
                        },
                        new
                        {
                            Id = 34,
                            AutorId = 2,
                            Cijena = 0.58119213654715207,
                            Naslov = "Autem nisi minima quisquam.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "Ex accusamus voluptatem minus quam aut dolor voluptatibus in eum. Ipsum provident velit ea sed voluptas perferendis omnis et debitis. Enim quo provident et qui repudiandae corporis perferendis quaerat. Sit quis debitis ipsa aut animi. Repellendus vitae voluptatum debitis."
                        },
                        new
                        {
                            Id = 35,
                            AutorId = 2,
                            Cijena = 0.91588870432036407,
                            Naslov = "Odio hic minus reprehenderit aut odio.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = @"Repellat error iste nemo sed voluptas veritatis accusamus.
Iure similique qui quo dolore sed ea error.
Aut voluptas dolorem ea."
                        },
                        new
                        {
                            Id = 36,
                            AutorId = 2,
                            Cijena = 0.28746139830325795,
                            Naslov = "Tempora sunt nihil dicta occaecati et in omnis.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "officia"
                        },
                        new
                        {
                            Id = 37,
                            AutorId = 2,
                            Cijena = 0.49074393533670524,
                            Naslov = "Atque nam in commodi est.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "et"
                        },
                        new
                        {
                            Id = 38,
                            AutorId = 2,
                            Cijena = 0.2421865119795252,
                            Naslov = "Aperiam id cumque.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "aperiam"
                        },
                        new
                        {
                            Id = 39,
                            AutorId = 2,
                            Cijena = 0.996635091955138,
                            Naslov = "Dolorem corrupti sint mollitia.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = @"Aut veritatis aut.
Dolor vel perferendis non dolore.
Modi officiis eveniet voluptas occaecati ipsa laborum id nihil porro.
Corrupti alias necessitatibus corrupti.
Autem qui facere libero eligendi.
Expedita officia nostrum corporis facere eos fuga soluta."
                        },
                        new
                        {
                            Id = 40,
                            AutorId = 2,
                            Cijena = 0.30926423720515528,
                            Naslov = "Ex quod aut nesciunt nisi ea corporis ducimus nemo.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "Aut dolorum inventore. Eos et iusto. Praesentium culpa ut iste eius."
                        },
                        new
                        {
                            Id = 41,
                            AutorId = 2,
                            Cijena = 0.91541020707944887,
                            Naslov = "Numquam nostrum placeat voluptatibus maxime quisquam autem.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "voluptatem"
                        },
                        new
                        {
                            Id = 42,
                            AutorId = 2,
                            Cijena = 0.15688205797080046,
                            Naslov = "Repudiandae perferendis molestiae corporis commodi.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = @"Nihil tempore dolore libero alias nihil et.
Ea est rem esse earum aperiam vel dicta.
Iste aut voluptatum reprehenderit.
Atque quibusdam ipsum sed aut quam vero."
                        },
                        new
                        {
                            Id = 43,
                            AutorId = 2,
                            Cijena = 0.52661795566166658,
                            Naslov = "Error fugit cum id.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "Placeat minima quas consequatur perferendis ea temporibus. Eum debitis sed laboriosam ratione consequatur. Delectus voluptatem velit amet ducimus dolores totam eligendi. At sed natus voluptates ullam ut et recusandae sed. Aut minus aut iure quos quia aut. Voluptatem magni eius occaecati aut voluptate officiis voluptatem."
                        },
                        new
                        {
                            Id = 44,
                            AutorId = 2,
                            Cijena = 0.80182833215306903,
                            Naslov = "Est occaecati consequuntur veniam qui soluta.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "vel"
                        },
                        new
                        {
                            Id = 45,
                            AutorId = 2,
                            Cijena = 0.24601385427918931,
                            Naslov = "Velit sed dignissimos ut modi laborum consequatur a doloribus voluptas.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = @"Eum ipsam error id suscipit consectetur.
Aperiam voluptatem quod doloremque."
                        },
                        new
                        {
                            Id = 46,
                            AutorId = 2,
                            Cijena = 0.033406760093479773,
                            Naslov = "Voluptate occaecati voluptatem exercitationem incidunt cum quia.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "rem"
                        },
                        new
                        {
                            Id = 47,
                            AutorId = 2,
                            Cijena = 0.81039635595418347,
                            Naslov = "Hic ullam in ea repudiandae nesciunt voluptas eligendi.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = @"Ut voluptatem architecto qui dolorum.
Nulla quae autem esse voluptatem fuga sed atque."
                        },
                        new
                        {
                            Id = 48,
                            AutorId = 2,
                            Cijena = 0.75007895368620703,
                            Naslov = "Provident doloremque quod enim ex veniam officiis expedita.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "autem"
                        },
                        new
                        {
                            Id = 49,
                            AutorId = 2,
                            Cijena = 0.079993265718218534,
                            Naslov = "Asperiores reiciendis suscipit.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = @"Omnis consequuntur modi.
Inventore tempore veniam nihil expedita ad.
Tempore velit sint aut praesentium incidunt nam rerum assumenda earum.
Ratione esse repellendus eum eveniet est illo in."
                        },
                        new
                        {
                            Id = 50,
                            AutorId = 2,
                            Cijena = 0.37203705002182957,
                            Naslov = "Aut sunt non soluta voluptatum quia.",
                            Obrisan = false,
                            OdobravateljId = 1,
                            Odobren = true,
                            Text = "Non fuga animi. Ea deserunt eum perferendis provident maxime tempore id. Ipsum et voluptatibus aut fuga incidunt est iste."
                        });
                });

            modelBuilder.Entity("SmartRead.API.Database.ClanakKategorija", b =>
                {
                    b.Property<int>("ClanakId")
                        .HasColumnType("int");

                    b.Property<int>("KategorijaId")
                        .HasColumnType("int");

                    b.HasKey("ClanakId", "KategorijaId");

                    b.HasIndex("KategorijaId");

                    b.ToTable("ClanakKategorije");
                });

            modelBuilder.Entity("SmartRead.API.Database.Drzava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drzave");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Bosna i Hercegovina"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Hrvatska"
                        });
                });

            modelBuilder.Entity("SmartRead.API.Database.Kategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Obrisan")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Kategorije");
                });

            modelBuilder.Entity("SmartRead.API.Database.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrzavaId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Kredit")
                        .HasColumnType("float");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Obrisan")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DrzavaId");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumRegistracije = new DateTime(2021, 7, 9, 8, 20, 26, 327, DateTimeKind.Local).AddTicks(6085),
                            DatumRodjenja = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrzavaId = 1,
                            Ime = "Maid",
                            Kredit = 0.0,
                            Mail = "maid.beslagic@edu.fit.ba",
                            Obrisan = false,
                            PasswordHash = "as+iQUHLZf5YVKsjqdDEGANu19YOPoXGRW1/Uh8n1vXJNM27pt7YlHTPaXnHSc3vUxczoViJNw9TdEyozGpIgQ==",
                            PasswordSalt = "7xfsmnn3ZiDRS7uYJkuIoQ==",
                            Prezime = "Bešlagić",
                            Username = "maid"
                        },
                        new
                        {
                            Id = 2,
                            DatumRegistracije = new DateTime(2021, 7, 9, 8, 20, 26, 337, DateTimeKind.Local).AddTicks(4037),
                            DatumRodjenja = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrzavaId = 1,
                            Ime = "Desktop",
                            Kredit = 0.0,
                            Mail = "desktop@edu.fit.ba",
                            Obrisan = false,
                            PasswordHash = "as+iQUHLZf5YVKsjqdDEGANu19YOPoXGRW1/Uh8n1vXJNM27pt7YlHTPaXnHSc3vUxczoViJNw9TdEyozGpIgQ==",
                            PasswordSalt = "7xfsmnn3ZiDRS7uYJkuIoQ==",
                            Prezime = "Admin",
                            Username = "desktop"
                        },
                        new
                        {
                            Id = 3,
                            DatumRegistracije = new DateTime(2021, 7, 9, 8, 20, 26, 337, DateTimeKind.Local).AddTicks(4854),
                            DatumRodjenja = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrzavaId = 1,
                            Ime = "Mobile",
                            Kredit = 0.0,
                            Mail = "mobile@edu.fit.ba",
                            Obrisan = false,
                            PasswordHash = "as+iQUHLZf5YVKsjqdDEGANu19YOPoXGRW1/Uh8n1vXJNM27pt7YlHTPaXnHSc3vUxczoViJNw9TdEyozGpIgQ==",
                            PasswordSalt = "7xfsmnn3ZiDRS7uYJkuIoQ==",
                            Prezime = "User",
                            Username = "mobile"
                        });
                });

            modelBuilder.Entity("SmartRead.API.Database.KorisnikClanak", b =>
                {
                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("ClanakId")
                        .HasColumnType("int");

                    b.Property<int>("BrojPosjeta")
                        .HasColumnType("int");

                    b.Property<bool>("Kupljen")
                        .HasColumnType("bit");

                    b.Property<int>("Ocjena")
                        .HasColumnType("int");

                    b.HasKey("KorisnikId", "ClanakId");

                    b.HasIndex("ClanakId");

                    b.ToTable("KorisnikClanci");
                });

            modelBuilder.Entity("SmartRead.API.Database.KorisnikKategorija", b =>
                {
                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("KategorijaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumPretplate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Obrisan")
                        .HasColumnType("bit");

                    b.HasKey("KorisnikId", "KategorijaId");

                    b.HasIndex("KategorijaId");

                    b.ToTable("KorisnikKategorije");
                });

            modelBuilder.Entity("SmartRead.API.Database.KorisnikPrijava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClanakId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pregledano")
                        .HasColumnType("bit");

                    b.Property<bool>("Uvazeno")
                        .HasColumnType("bit");

                    b.Property<DateTime>("VrijemePrijave")
                        .HasColumnType("datetime2");

                    b.Property<int>("VrstaPrijave")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClanakId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("KorisnikPrijave");
                });

            modelBuilder.Entity("SmartRead.API.Database.KorisnikUloga", b =>
                {
                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("KorisnikId", "UlogaId");

                    b.HasIndex("UlogaId");

                    b.ToTable("KorisnikUloge");

                    b.HasData(
                        new
                        {
                            KorisnikId = 1,
                            UlogaId = 1
                        },
                        new
                        {
                            KorisnikId = 1,
                            UlogaId = 2
                        },
                        new
                        {
                            KorisnikId = 2,
                            UlogaId = 1
                        },
                        new
                        {
                            KorisnikId = 3,
                            UlogaId = 2
                        });
                });

            modelBuilder.Entity("SmartRead.API.Database.Like", b =>
                {
                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("ClanakId")
                        .HasColumnType("int");

                    b.HasKey("KorisnikId", "ClanakId");

                    b.HasIndex("ClanakId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("SmartRead.API.Database.Uloga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uloge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "BasicUser"
                        });
                });

            modelBuilder.Entity("SmartRead.API.Database.Uplata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Iznos")
                        .HasColumnType("real");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Uplate");
                });

            modelBuilder.Entity("SmartRead.API.Database.Clanak", b =>
                {
                    b.HasOne("SmartRead.API.Database.Korisnik", "Autor")
                        .WithMany("Clanci")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRead.API.Database.Korisnik", "Odobravatelj")
                        .WithMany()
                        .HasForeignKey("OdobravateljId");
                });

            modelBuilder.Entity("SmartRead.API.Database.ClanakKategorija", b =>
                {
                    b.HasOne("SmartRead.API.Database.Clanak", "Clanak")
                        .WithMany("Kategorije")
                        .HasForeignKey("ClanakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRead.API.Database.Kategorija", "Kategorija")
                        .WithMany()
                        .HasForeignKey("KategorijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartRead.API.Database.Korisnik", b =>
                {
                    b.HasOne("SmartRead.API.Database.Drzava", "Drzava")
                        .WithMany()
                        .HasForeignKey("DrzavaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartRead.API.Database.KorisnikClanak", b =>
                {
                    b.HasOne("SmartRead.API.Database.Clanak", "Clanak")
                        .WithMany()
                        .HasForeignKey("ClanakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRead.API.Database.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartRead.API.Database.KorisnikKategorija", b =>
                {
                    b.HasOne("SmartRead.API.Database.Kategorija", "Kategorija")
                        .WithMany()
                        .HasForeignKey("KategorijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRead.API.Database.Korisnik", "Korisnik")
                        .WithMany("PretplaceneKategorije")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartRead.API.Database.KorisnikPrijava", b =>
                {
                    b.HasOne("SmartRead.API.Database.Clanak", "Clanak")
                        .WithMany("Prijave")
                        .HasForeignKey("ClanakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRead.API.Database.Korisnik", "Korisnik")
                        .WithMany("PrijavljeniClanci")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartRead.API.Database.KorisnikUloga", b =>
                {
                    b.HasOne("SmartRead.API.Database.Korisnik", "Korisnik")
                        .WithMany("Uloge")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRead.API.Database.Uloga", "Uloga")
                        .WithMany()
                        .HasForeignKey("UlogaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartRead.API.Database.Like", b =>
                {
                    b.HasOne("SmartRead.API.Database.Clanak", "Clanak")
                        .WithMany()
                        .HasForeignKey("ClanakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRead.API.Database.Korisnik", "Korisnik")
                        .WithMany("Likes")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartRead.API.Database.Uplata", b =>
                {
                    b.HasOne("SmartRead.API.Database.Korisnik", "Korisnik")
                        .WithMany("Uplate")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
